name: covid
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alabaster=0.7.16=py311h06a4308_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - babel=2.16.0=py311h06a4308_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotlicffi=1.0.9.2=py311h6a678d5_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.3=py311hdf67eae_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h3c4dab8_0
  - docutils=0.21.2=py311h06a4308_0
  - double-conversion=3.3.1=h5888daf_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.0=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=11.5.1=h15599e2_0
  - icu=75.1=he02047a_0
  - idna=3.7=py311h06a4308_0
  - imagesize=1.4.1=py311h06a4308_0
  - jinja2=3.1.6=py311h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=36_h0358290_openblas
  - libclang-cpp21.1=21.1.0=default_h99862b1_1
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=36_h47877c9_openblas
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.6=py311h38be061_1
  - matplotlib-base=3.10.6=py311h0f3be63_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.3=py311h2e04523_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openpyxl=3.1.5=py311h534898f_2
  - openssl=3.5.3=h26f9b46_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py311hed34c8f_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h1321c63_0
  - pillow=11.3.0=py311h98278a2_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.23=py311h06a4308_0
  - pygments=2.19.1=py311h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.2=py311h72d58bf_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.13=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.2=h5bd77bc_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=py311h06a4308_0
  - roman-numerals-py=3.1.0=py311h06a4308_0
  - scipy=1.16.2=py311h1e13796_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snowballstemmer=3.0.1=py311h06a4308_0
  - sphinx=8.2.3=py311h5eee18b_0
  - sphinx-rtd-theme=3.0.2=pyhd3eb1b0_0
  - sphinx_rtd_theme=3.0.2=py311h06a4308_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jquery=4.1=py311h06a4308_1
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - statsmodels=0.14.5=py311hb0beb2c_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py311h49ec1c0_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py311h49ec1c0_1
  - urllib3=2.5.0=py311h06a4308_0
  - wayland=1.24.0=h3e06ad9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accessible-pygments==0.0.5
      - beautifulsoup4==4.14.2
      - pydata-sphinx-theme==0.15.4
      - soupsieve==2.8
      - sphinx-book-theme==1.1.4
      - typing-extensions==4.15.0
prefix: /home/siddhant/miniconda3/envs/covid
